// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBru_4KxptpEVc0YCm9N5gEDRpDkGbqM',
    appId: '1:480649239781:web:c157c3bd56c0099611880c',
    messagingSenderId: '480649239781',
    projectId: 'car-quest-app',
    authDomain: 'car-quest-app.firebaseapp.com',
    storageBucket: 'car-quest-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6R9ymMtH9nr79I7TrCoOq4JeBKj8NVpA',
    appId: '1:480649239781:android:43e748486f76f1f311880c',
    messagingSenderId: '480649239781',
    projectId: 'car-quest-app',
    storageBucket: 'car-quest-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03XsNrZXLqsIwLt8jdGyx5_GBelmf8U0',
    appId: '1:480649239781:ios:df940f05c38550e011880c',
    messagingSenderId: '480649239781',
    projectId: 'car-quest-app',
    storageBucket: 'car-quest-app.appspot.com',
    iosBundleId: 'com.example.carquestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03XsNrZXLqsIwLt8jdGyx5_GBelmf8U0',
    appId: '1:480649239781:ios:df940f05c38550e011880c',
    messagingSenderId: '480649239781',
    projectId: 'car-quest-app',
    storageBucket: 'car-quest-app.appspot.com',
    iosBundleId: 'com.example.carquestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBBru_4KxptpEVc0YCm9N5gEDRpDkGbqM',
    appId: '1:480649239781:web:d451d11e523967d211880c',
    messagingSenderId: '480649239781',
    projectId: 'car-quest-app',
    authDomain: 'car-quest-app.firebaseapp.com',
    storageBucket: 'car-quest-app.appspot.com',
  );

}